### ISSUE TITLE
Merge with Proxmark/proxmark3 ?

### ISSUE THREAD

**Issue by pwpiwi** [chrisfu/homebrew-tap#1]
MacOS is not my friend, but can we merge this with Proxmark3 master branch? Is it only proxmark3.rb and arm-none-eabi-gcc.rb we would need to add?

**Comment by chrisfu** [comment]
Hi there,

Yep that's absolutely correct. AFAIK it would need to live in the root of
the repo though, so there's that to consider.

The alternative is to add it to the wiki and other docs, and create
Proxmark/proxmark3-tap and make that the official Mac Homebrew tap. Bit
cleaner than way.

Over time you may end up accepting other Homebrew Formula submissions that
could go in there too.

Cheers,

Chris

**Comment by pwpiwi** [comment]
What would we need to change in the wiki? [https://github.com/Proxmark/proxmark3/wiki/OSX](url) Would you volunteer to update it?
